In [4]:
import pandas as pd
import numpy as np

df=pd.read_csv('Customer_Behaviour_Survey_responses.csv')
print(df.head())

            Timestamp Age   Gender Current State or Union Territory     City  \
0  6/10/2021 22:41:22   21    Male                    Uttar Pradesh  Lucknow   
1  6/11/2021 16:08:43   21    Male                    Uttar Pradesh  Lucknow   
2  6/11/2021 16:12:18   19  Female                    Uttar Pradesh  Kanpur    
3  6/11/2021 16:14:29   25    Male                      Maharashtra   Mumbai   
4  6/11/2021 16:18:31   22  Female                       Chandigarh      NaN   

  Which Tier does your city belong to? Marital Status  \
0                               Tier 2    Not Married   
1                               Tier 2    Not Married   
2                               Tier 2    Not Married   
3                               Tier 1    Not Married   
4                               Tier 2    Not Married   

  What is your financial status?  \
0                        Student   
1                        Student   
2                        Student   
3                    Regular Job

In [5]:
print(df.columns)

Index(['Timestamp', 'Age ', 'Gender', 'Current State or Union Territory',
       'City', 'Which Tier does your city belong to?', 'Marital Status',
       'What is your financial status?',
       'Say for example , a similar product with similar features is being sold at half the price by an unknown seller as compared to a branded product. Would you purchase that product? or Simply Do you prefer cost over brands?',
       'What is the Product Category that you shop very frequently?',
       'How much time do you spend while picking the right product to buy?',
       'On a scale of 1 to 5 , how often do you shop in the selected product category monthly? ',
       'What is the average money that you spend while shopping the above items in one time?',
       'Which product among Electronics do you shop very often?',
       'Which product among Fashion do you shop very often?',
       'Which product among Clothing do you shop very often?',
       'Which OTT subscriptions do you use the most

In [6]:
rename_cols = {
    'Timestamp':'timestamp',
    'Age ':'age',
    'Gender':'gender',
    'Current State or Union Territory':'state',
    'City':'city',
    'Which Tier does your city belong to?':'city_tier',
    'Marital Status':'martial_status',
    'What is your financial status?':'financial_status',
    'Say for example , a similar product with similar features is being sold at half the price by an unknown seller as compared to a branded product. Would you purchase that product? or Simply Do you prefer cost over brands?':'cost_over_brand_preference',
    'What is the Product Category that you shop very frequently?':'product_category',
    'How much time do you spend while picking the right product to buy?':'decision_time',
    'On a scale of 1 to 5 , how often do you shop in the selected product category monthly? ':'monthly_shopping_frequency',
    'What is the average money that you spend while shopping the above items in one time?':'avg_spend_per_purchase',
    'Which product among Electronics do you shop very often?':'frequent_electronics_product',
    'Which product among Fashion do you shop very often?':'frequent_fashion_product',
    'Which product among Clothing do you shop very often?':'frequent_clothing_product',
    'Which OTT subscriptions do you use the most?':'ott_subscription',
    'Which type of Books do you buy the most?':'book_type'
}

df.rename(columns=rename_cols, inplace=True)

In [7]:
df.columns

Index(['timestamp', 'age', 'gender', 'state', 'city', 'city_tier',
       'martial_status', 'financial_status', 'cost_over_brand_preference',
       'product_category', 'decision_time', 'monthly_shopping_frequency',
       'avg_spend_per_purchase', 'frequent_electronics_product',
       'frequent_fashion_product', 'frequent_clothing_product',
       'ott_subscription', 'book_type'],
      dtype='object')

In [8]:
df.head()

timestamp age  gender          state     city city_tier  \
0  6/10/2021 22:41:22  21    Male  Uttar Pradesh  Lucknow    Tier 2   
1  6/11/2021 16:08:43  21    Male  Uttar Pradesh  Lucknow    Tier 2   
2  6/11/2021 16:12:18  19  Female  Uttar Pradesh  Kanpur     Tier 2   
3  6/11/2021 16:14:29  25    Male    Maharashtra   Mumbai    Tier 1   
4  6/11/2021 16:18:31  22  Female     Chandigarh      NaN    Tier 2   

  martial_status financial_status cost_over_brand_preference  \
0    Not Married          Student                         No   
1    Not Married          Student                         No   
2    Not Married          Student                         No   
3    Not Married      Regular Job                        Yes   
4    Not Married      Freelancing                         No   

                             product_category    decision_time  \
0                                 Electronics  Couple of Weeks   
1                                 Electronics  Couple of Weeks   
2  Fashion ( Makeup, cosmetics, Perfume etc )     Within a day   
3                                    Clothing  An entire month   
4  Fashion ( Makeup, cosmetics, Perfume etc )  Couple of Weeks   

   monthly_shopping_frequency avg_spend_per_purchase  \
0                           2    Between ₹1000-₹5000   
1                           2    Between ₹1000-₹5000   
2                           4    Between ₹1000-₹5000   
3                           3     Greater than ₹5000   
4                           4    Between ₹1000-₹5000   

                      frequent_electronics_product frequent_fashion_product  \
0  Utility Devices ( like pen drive , cables etc )                      NaN   
1  Utility Devices ( like pen drive , cables etc )                      NaN   
2                                              NaN                Jewellery   
3                                              NaN                      NaN   
4                                              NaN                Cosmetics   

  frequent_clothing_product ott_subscription book_type  
0                       NaN              NaN       NaN  
1                       NaN              NaN       NaN  
2                       NaN              NaN       NaN  
3         T-shirts / Shirts              NaN       NaN  
4                       NaN              NaN       NaN

In [9]:
df['timestamp'].unique()

array(['6/10/2021 22:41:22', '6/11/2021 16:08:43', '6/11/2021 16:12:18',
       '6/11/2021 16:14:29', '6/11/2021 16:18:31', '6/11/2021 16:23:22',
       '6/11/2021 16:29:05', '6/11/2021 16:32:33', '6/11/2021 16:35:23',
       '6/11/2021 16:37:34', '6/11/2021 16:38:37', '6/11/2021 16:44:46',
       '6/11/2021 16:56:24', '6/11/2021 16:59:43', '6/11/2021 17:00:52',
       '6/11/2021 17:02:34', '6/11/2021 17:06:40', '6/11/2021 23:01:35',
       '6/11/2021 23:02:39', '6/11/2021 23:04:31', '6/11/2021 23:05:37',
       '6/11/2021 23:09:04', '6/12/2021 14:03:34', '6/12/2021 14:34:20',
       '6/12/2021 14:37:01', '6/12/2021 14:38:34', '6/12/2021 15:35:59',
       '6/12/2021 15:42:11', '6/12/2021 15:43:31', '6/12/2021 15:45:01',
       '6/12/2021 17:35:51', '6/12/2021 17:38:09', '6/12/2021 17:40:00',
       '6/12/2021 17:41:35', '6/12/2021 17:44:21', '6/12/2021 18:15:07',
       '6/12/2021 18:16:10', '6/12/2021 18:16:51', '6/12/2021 18:17:42',
       '6/12/2021 18:19:12', '6/12/2021 18:25:31', 

In [10]:
df['timestamp']=pd.to_datetime(df['timestamp'], format='%m/%d/%Y %H:%M:%S', errors='coerce')

In [11]:
df['timestamp'].dtypes

dtype('<M8[ns]')

In [12]:
df[df['timestamp'].isna()]
#Check for failed conversions

Empty DataFrame
Columns: [timestamp, age, gender, state, city, city_tier, martial_status, financial_status, cost_over_brand_preference, product_category, decision_time, monthly_shopping_frequency, avg_spend_per_purchase, frequent_electronics_product, frequent_fashion_product, frequent_clothing_product, ott_subscription, book_type]
Index: []

In [13]:
df['date']=df['timestamp'].dt.date
df['date']=df['timestamp'].dt.year
df['month']=df['timestamp'].dt.month
df['month_name']=df['timestamp'].dt.month_name()
df['day']=df['timestamp'].dt.day
df['day_name']=df['timestamp'].dt.day_name()
df['hour']=df['timestamp'].dt.hour

In [14]:
df.head(2)

timestamp age gender          state     city city_tier  \
0 2021-06-10 22:41:22  21   Male  Uttar Pradesh  Lucknow    Tier 2   
1 2021-06-11 16:08:43  21   Male  Uttar Pradesh  Lucknow    Tier 2   

  martial_status financial_status cost_over_brand_preference product_category  \
0    Not Married          Student                         No      Electronics   
1    Not Married          Student                         No      Electronics   

   ... frequent_fashion_product  frequent_clothing_product ott_subscription  \
0  ...                      NaN                        NaN              NaN   
1  ...                      NaN                        NaN              NaN   

  book_type  date month month_name day  day_name  hour  
0       NaN  2021     6       June  10  Thursday    22  
1       NaN  2021     6       June  11    Friday    16  

[2 rows x 24 columns]

In [15]:
#Delete timestamp Column
df.drop(columns=['timestamp'], inplace=True)

In [16]:
df['age'].unique()

array(['21', '19', '25', '22', '43', '20', '32', '26', '18', '52', '24',
       '27', '33', '29', '16', '17', '55', '31', '58', '15', '30', '48',
       '23', '28', '54', '45', '35', '41', '51', '40', '37', '53', '50',
       '55 years', '34', '56', '62', '49', 'Anurag Dubey', '39', '36',
       '46', '42'], dtype=object)

In [17]:
df['age']=df['age'].str.extract(r'(\d+)').astype(float)

In [18]:
df['age'].dtypes

dtype('float64')

In [19]:
df.loc[(df['age']<18) | (df['age']>60), 'age']=np.nan

In [20]:
df['age'].unique()
df['age'].isna().sum()

18

In [21]:
df['city'].unique()

array(['Lucknow', 'Kanpur ', 'Mumbai', nan, 'Ludhiana', 'Karnal ',
       'Kurukshetra', 'Gandhinagar', 'Ajmer', 'Gurgaon', 'Shimla',
       'Jammu', 'Bangalore', 'Jodhpur', 'Chennai ', 'Kolkata', 'Pune',
       'Amritsar', 'Patiala', 'Pune ', 'Bikaner ', 'Rohtak ', 'Nashik ',
       'Noida', 'Patna', 'Udaipur', 'Lucknow ', 'Karnal', 'Delhi',
       'Jullunder', 'Ahmedabad', 'Jaipur', 'Ambala', 'Bathinda',
       'Ranchi ', 'Hyderabad', 'Guwahati', 'Rohtak', 'Rajkot ',
       'Greater noida ', 'Thane', 'New Delhi', 'Bhopal', 'Aligarh',
       'Agra', 'Bhiwandi', 'Jalandar', 'Mandi', 'Gurgaon ', 'Yamunanagar',
       'Mohali', 'Chandigarh', 'New delhi', 'Gaya', 'Chandigarh ',
       'Mumbai ', 'Vasant kunj ', 'Agartala', 'Hooghly ', 'GREATER NOIDA',
       'Panipat', 'Panchkula ', 'New Delhi ', 'Moradabad ',
       'Greater Noida', 'Ghaziabad ', 'Jind', 'Lucknow or', 'Faridabad ',
       'Boisar ', 'Gorakhpur', 'Vadodara ', 'Hubli', 'Khurja',
       'NEW DELHI', 'Vishakapatnam', 'Raigar

In [22]:
df['city']=df['city'].str.strip().str.title()

In [23]:
df['city'].unique()

array(['Lucknow', 'Kanpur', 'Mumbai', nan, 'Ludhiana', 'Karnal',
       'Kurukshetra', 'Gandhinagar', 'Ajmer', 'Gurgaon', 'Shimla',
       'Jammu', 'Bangalore', 'Jodhpur', 'Chennai', 'Kolkata', 'Pune',
       'Amritsar', 'Patiala', 'Bikaner', 'Rohtak', 'Nashik', 'Noida',
       'Patna', 'Udaipur', 'Delhi', 'Jullunder', 'Ahmedabad', 'Jaipur',
       'Ambala', 'Bathinda', 'Ranchi', 'Hyderabad', 'Guwahati', 'Rajkot',
       'Greater Noida', 'Thane', 'New Delhi', 'Bhopal', 'Aligarh', 'Agra',
       'Bhiwandi', 'Jalandar', 'Mandi', 'Yamunanagar', 'Mohali',
       'Chandigarh', 'Gaya', 'Vasant Kunj', 'Agartala', 'Hooghly',
       'Panipat', 'Panchkula', 'Moradabad', 'Ghaziabad', 'Jind',
       'Lucknow Or', 'Faridabad', 'Boisar', 'Gorakhpur', 'Vadodara',
       'Hubli', 'Khurja', 'Vishakapatnam', 'Raigarh', 'Jamshedpur',
       'Surat', 'Srinagar', 'Vellore', 'Ujjain', 'Kashmir', 'Dehradun',
       'Nellore', 'Kota'], dtype=object)

In [24]:
city_map = {
    'Lucknow Or':'Lucknow',
    'Greater Noida':'Noida',
    'New Delhi':'Delhi'
}

df['city']=df['city'].replace(city_map)

In [25]:
df['city'].unique()

array(['Lucknow', 'Kanpur', 'Mumbai', nan, 'Ludhiana', 'Karnal',
       'Kurukshetra', 'Gandhinagar', 'Ajmer', 'Gurgaon', 'Shimla',
       'Jammu', 'Bangalore', 'Jodhpur', 'Chennai', 'Kolkata', 'Pune',
       'Amritsar', 'Patiala', 'Bikaner', 'Rohtak', 'Nashik', 'Noida',
       'Patna', 'Udaipur', 'Delhi', 'Jullunder', 'Ahmedabad', 'Jaipur',
       'Ambala', 'Bathinda', 'Ranchi', 'Hyderabad', 'Guwahati', 'Rajkot',
       'Thane', 'Bhopal', 'Aligarh', 'Agra', 'Bhiwandi', 'Jalandar',
       'Mandi', 'Yamunanagar', 'Mohali', 'Chandigarh', 'Gaya',
       'Vasant Kunj', 'Agartala', 'Hooghly', 'Panipat', 'Panchkula',
       'Moradabad', 'Ghaziabad', 'Jind', 'Faridabad', 'Boisar',
       'Gorakhpur', 'Vadodara', 'Hubli', 'Khurja', 'Vishakapatnam',
       'Raigarh', 'Jamshedpur', 'Surat', 'Srinagar', 'Vellore', 'Ujjain',
       'Kashmir', 'Dehradun', 'Nellore', 'Kota'], dtype=object)

In [26]:
df['product_category'].unique()

array(['Electronics', 'Fashion ( Makeup, cosmetics, Perfume etc )',
       'Clothing',
       'OTT Subscriptions ( Netflix , Amazon , prime video etc )',
       'Books', 'Home decor ', 'Kitchen utensils', 'Netflux',
       'Daily use items ', 'Food items ', 'Food', 'Household goods ',
       'Grocery', 'Daily needs', 'Liquor', 'Household products',
       'House products', 'Household', 'Home products', 'Food products'],
      dtype=object)

In [27]:
df['product_category']=df['product_category'].str.strip().str.title()

In [28]:
df['product_category'].unique()

array(['Electronics', 'Fashion ( Makeup, Cosmetics, Perfume Etc )',
       'Clothing',
       'Ott Subscriptions ( Netflix , Amazon , Prime Video Etc )',
       'Books', 'Home Decor', 'Kitchen Utensils', 'Netflux',
       'Daily Use Items', 'Food Items', 'Food', 'Household Goods',
       'Grocery', 'Daily Needs', 'Liquor', 'Household Products',
       'House Products', 'Household', 'Home Products', 'Food Products'],
      dtype=object)

In [29]:
category_map = {
    'Fashion ( Makeup, Cosmetics, Perfume Etc )':'Fashion',
    'Ott Subscriptions ( Netflix , Amazon , Prime Video Etc )':'Ott Subscription',
    'Netflux':'Ott Subscription',
    'Kitchen utensils':'Kitchen',
    'Daily use items ':'Daily needs',
    'Household Goods':'Household',
    'Household Products':'Household',
    'House Products':'Household',
    'Home Products':'Household',
    'Food Items':'Food',
    'Food Products':'Food'

}
df['product_category']=df['product_category'].replace(category_map)

In [30]:
df['product_category'].unique()

array(['Electronics', 'Fashion', 'Clothing', 'Ott Subscription', 'Books',
       'Home Decor', 'Kitchen Utensils', 'Daily Use Items', 'Food',
       'Household', 'Grocery', 'Daily Needs', 'Liquor'], dtype=object)

In [31]:
df['decision_time'].unique()

array(['Couple of Weeks', 'Within a day', 'An entire month',
       'Less than hour', 'Depends on type of product',
       'Sometimes I keep.in a wishlist nf', 'One week '], dtype=object)

In [32]:
df['decision_time']=df['decision_time'].str.strip().str.title()

In [33]:
decision_map = {
    'Less Than Hour': 'Less Than 1 Hour',
    'Within A Day': 'Within 1 Day',
    'One Week': 'Within 1 Week',
    'Couple Of Weeks': '1–2 Weeks',
    'An Entire Month': 'More Than 1 Month',
    'Depends On Type Of Product': 'Depends',
    'Sometimes I Keep.In A Wishlist Nf': 'Wishlist'
}

df['decision_time']=df['decision_time'].replace(decision_map)

In [34]:
df['decision_time'].unique()

array(['1–2 Weeks', 'Within 1 Day', 'More Than 1 Month',
       'Less Than 1 Hour', 'Depends', 'Wishlist', 'Within 1 Week'],
      dtype=object)

In [35]:
df['monthly_shopping_frequency'].unique()

array([2, 4, 3, 1, 5, 0], dtype=int64)

In [36]:
df['monthly_shopping_frequency']=pd.to_numeric(df['monthly_shopping_frequency'], errors='coerce')

In [37]:
avg_spend_map = {
    'Between ₹1000-₹5000':3000,
    'Greater than ₹5000':6000,
    'Less Than ₹1000':500
}

df['avg_spend_per_purchase']=df['avg_spend_per_purchase'].replace(avg_spend_map)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17660\15307108.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['avg_spend_per_purchase']=df['avg_spend_per_purchase'].replace(avg_spend_map)


In [38]:
df['avg_spend_category']=df['avg_spend_per_purchase']

In [39]:
df['avg_spend_category'].unique()

array([3000, 6000,  500], dtype=int64)

In [40]:
df.drop(columns='avg_spend_per_purchase', inplace=True)

In [41]:
df['frequent_electronics_product'].unique()

array(['Utility Devices ( like pen drive , cables etc )', nan,
       'Mouse / Keyboard', 'Headphones / Earphones', 'Speakers', 'Mobile',
       'All of the above'], dtype=object)

In [42]:
df['frequent_electronics_product']=df['frequent_electronics_product'].str.strip().str.lower()

In [43]:
mapping = {
    'utility devices ( like pen drive , cables etc )': 'utility devices',
    'mouse / keyboard': 'mouse & keyboard',
    'headphones / earphones': 'headphones',
    'all of the above': 'multiple products'
}

df['frequent_electronics_product']=df['frequent_electronics_product'].replace(mapping)

In [44]:
df['frequent_electronics_product'].unique()

array(['utility devices', nan, 'mouse & keyboard', 'headphones',
       'speakers', 'mobile', 'multiple products'], dtype=object)

In [45]:
df['frequent_fashion_product'].unique()

array([nan, 'Jewellery', 'Cosmetics', 'Perfumes', 'Purses / Bags',
       'Wrist Watch', 'Shirt'], dtype=object)

In [46]:
df['frequent_fashion_product']=df['frequent_fashion_product'].str.strip().str.lower()

In [47]:
fashion_mapping = {
    'purses / bags': 'bags',
    'wrist watch': 'watches',
    'shirt': 'apparel'
}

df['frequent_fashion_product']=df['frequent_fashion_product'].replace(fashion_mapping)

In [48]:
df['frequent_fashion_product'].unique()

array([nan, 'jewellery', 'cosmetics', 'perfumes', 'bags', 'watches',
       'apparel'], dtype=object)

In [49]:
df['frequent_clothing_product'].unique()

array([nan, 'T-shirts / Shirts', 'Shoes', 'Lower', 'Dresses',
       'Kurtis, lehenga, ethnic wear'], dtype=object)

In [50]:
df['frequent_clothing_product']=df['frequent_clothing_product'].str.strip().str.lower()

In [51]:
clothing_mapping = {
    't-shirts / shirts': 'tops',
    'lower': 'bottomwear',
    'shoes': 'footwear',
    'dresses': 'dresses',
    'kurtis, lehenga, ethnic wear': 'ethnic wear'
}

df['frequent_clothing_product']=df['frequent_clothing_product'].replace(clothing_mapping)

In [52]:
df['frequent_clothing_product'].unique()

array([nan, 'tops', 'footwear', 'bottomwear', 'dresses', 'ethnic wear'],
      dtype=object)

In [53]:
df['ott_subscription'].unique()

array([nan, 'Disney Hotstar', 'ALT Balaji', 'Amazon Prime', 'Sony Liv',
       'Netflix'], dtype=object)

In [54]:
df['ott_subscription']=df['ott_subscription'].str.strip().str.lower()

In [55]:
ott_mapping = {
    'disney hotstar': 'hotstar',
    'amazon prime': 'prime video',
    'sony liv': 'sonyliv',
    'alt balaji': 'altbalaji'
}

df['ott_subscription']=df['ott_subscription'].replace(ott_mapping)

In [56]:
df['ott_subscription'].unique()

array([nan, 'hotstar', 'altbalaji', 'prime video', 'sonyliv', 'netflix'],
      dtype=object)

In [57]:
df['book_type'].unique()

array([nan, 'Fiction', 'Romance', 'Adventure / Crime', 'Education',
       'Comics', 'Finance ', 'Knowledge', 'Educational '], dtype=object)

In [58]:
df['book_type']=df['book_type'].str.strip().str.lower()

In [59]:
book_mapping = {
    'educational': 'education',
    'education': 'education',
    'adventure / crime': 'adventure & crime',
    'finance': 'finance'
}

df['book_type']=df['book_type'].replace(book_mapping)

In [60]:
df['book_type'].unique()

array([nan, 'fiction', 'romance', 'adventure & crime', 'education',
       'comics', 'finance', 'knowledge'], dtype=object)

In [61]:
df.head(5)

age  gender          state     city city_tier martial_status  \
0  21.0    Male  Uttar Pradesh  Lucknow    Tier 2    Not Married   
1  21.0    Male  Uttar Pradesh  Lucknow    Tier 2    Not Married   
2  19.0  Female  Uttar Pradesh   Kanpur    Tier 2    Not Married   
3  25.0    Male    Maharashtra   Mumbai    Tier 1    Not Married   
4  22.0  Female     Chandigarh      NaN    Tier 2    Not Married   

  financial_status cost_over_brand_preference product_category  \
0          Student                         No      Electronics   
1          Student                         No      Electronics   
2          Student                         No          Fashion   
3      Regular Job                        Yes         Clothing   
4      Freelancing                         No          Fashion   

       decision_time  ...  frequent_clothing_product ott_subscription  \
0          1–2 Weeks  ...                        NaN              NaN   
1          1–2 Weeks  ...                        NaN              NaN   
2       Within 1 Day  ...                        NaN              NaN   
3  More Than 1 Month  ...                       tops              NaN   
4          1–2 Weeks  ...                        NaN              NaN   

  book_type  date month month_name  day  day_name hour  avg_spend_category  
0       NaN  2021     6       June   10  Thursday   22                3000  
1       NaN  2021     6       June   11    Friday   16                3000  
2       NaN  2021     6       June   11    Friday   16                3000  
3       NaN  2021     6       June   11    Friday   16                6000  
4       NaN  2021     6       June   11    Friday   16                3000  

[5 rows x 23 columns]

In [62]:
#Create a copy (best practice)
df_clean=df.copy()

In [63]:
#Standardize column names
df_clean.columns=(df_clean.columns.str.strip().str.lower().str.replace(' ','_'))

In [64]:
#Clean numeric columns
df_clean['age']=df_clean['age'].astype('Int64')
df_clean['avg_spend_category']=df_clean['avg_spend_category'].astype('int')

In [65]:
#Standardize ALL text columns
text_cols = df_clean.select_dtypes(include='object').columns

df_clean[text_cols]=df_clean[text_cols].apply(lambda x:x.str.strip().str.lower())

In [66]:
#Handle missing values
df_clean['city']=df_clean['city'].fillna('unknown')
df_clean['frequent_clothing_product']=df_clean['frequent_clothing_product'].fillna('not specified')
df_clean['ott_subscription']=df_clean['ott_subscription'].fillna('no subscription')
df_clean['book_type']=df_clean['book_type'].fillna('not specified')

In [67]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 254 entries, 0 to 253
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype 
---  ------                        --------------  ----- 
 0   age                           236 non-null    Int64 
 1   gender                        254 non-null    object
 2   state                         254 non-null    object
 3   city                          254 non-null    object
 4   city_tier                     254 non-null    object
 5   martial_status                254 non-null    object
 6   financial_status              254 non-null    object
 7   cost_over_brand_preference    254 non-null    object
 8   product_category              254 non-null    object
 9   decision_time                 254 non-null    object
 10  monthly_shopping_frequency    254 non-null    int64 
 11  frequent_electronics_product  49 non-null     object
 12  frequent_fashion_product      39 non-null     object
 13  frequent_clothing_pr

In [68]:
df_clean.isnull().sum()

age                              18
gender                            0
state                             0
city                              0
city_tier                         0
martial_status                    0
financial_status                  0
cost_over_brand_preference        0
product_category                  0
decision_time                     0
monthly_shopping_frequency        0
frequent_electronics_product    205
frequent_fashion_product        215
frequent_clothing_product         0
ott_subscription                  0
book_type                         0
date                              0
month                             0
month_name                        0
day                               0
day_name                          0
hour                              0
avg_spend_category                0
dtype: int64

In [69]:
#Fill with median
df_clean['age']=df_clean['age'].fillna(df_clean['age'].median())

In [70]:
df_clean['frequent_electronics_product'] = ( df_clean['frequent_electronics_product'].fillna('not applicable'))
df_clean['frequent_fashion_product']=(df_clean['frequent_fashion_product'].fillna('not applicable'))


In [71]:
df_clean.isnull().sum()

age                             0
gender                          0
state                           0
city                            0
city_tier                       0
martial_status                  0
financial_status                0
cost_over_brand_preference      0
product_category                0
decision_time                   0
monthly_shopping_frequency      0
frequent_electronics_product    0
frequent_fashion_product        0
frequent_clothing_product       0
ott_subscription                0
book_type                       0
date                            0
month                           0
month_name                      0
day                             0
day_name                        0
hour                            0
avg_spend_category              0
dtype: int64

In [72]:
import pandas as pd
from sqlalchemy import create_engine


engine = create_engine(
    "mssql+pyodbc://localhost/ECOMMERCE_DB?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)


df_clean.to_sql(
    name='ecommerce_user_behavior',
    con=engine,
    if_exists='replace',   
    index=False
)

72

In [73]:
df_clean.columns

Index(['age', 'gender', 'state', 'city', 'city_tier', 'martial_status',
       'financial_status', 'cost_over_brand_preference', 'product_category',
       'decision_time', 'monthly_shopping_frequency',
       'frequent_electronics_product', 'frequent_fashion_product',
       'frequent_clothing_product', 'ott_subscription', 'book_type', 'date',
       'month', 'month_name', 'day', 'day_name', 'hour', 'avg_spend_category'],
      dtype='object')